src/MapUtil/MapUtil.js, src/MapUtil/MapUtil.spec.js
Compare https://github.com/terrestris/ol-util/pull/16
=> Add support for OlSourceImageWMS to getLegendGraphicUrl method (for ol5)

src/MapUtil/MapUtil.js, src/MapUtil/MapUtil.spec.js
=> Fix getLegendGraphicUrl to not append multiple questionmarks

src/FeatureUtil/FeatureUtil.js, src/FeatureUtil/FeatureUtil.spec.js
=> Pass values through a customizable function before replacing in template

src/GeometryUtil/GeometryUtil.js
Title says it all. Please review.
=> Fix minors in the docs of geometry util

src/MapUtil/MapUtil.js
Title says it all. Please review.
=> Fix minors in the docs of map util

.vscode/launch.json
=> Added config for jest test debugging with vscode editor

src/WfsFilterUtil/WfsFilterUtil.js
Title says it all. Please review.
=> Cosmetic changes

README.md
=> Update the README to link to API docs

package.json
=> Update @terrestris/base-util to the latest version

.gitignore, jest.config.js
Title says it all, please review.
=> Ignore coverage of test util file

src/ProjectionUtil/ProjectionUtil.js, src/ProjectionUtil/ProjectionUtil.spec.js
This also revealed an issue when the defaults shouldn't be initialized.
Please review.
=> Add some tests for the projecton utility

jest.config.js, src/AnimateUtil/AnimateUtil.spec.js
Title says it all.
A cone of ice cream to the one that makes the test mentioned in the comment run and pass.
Please review.
=> Fix indentation and add a comment

package.json
=> chore(package): update documentation to version 9.2.1

README.md, src/CapabilitiesUtil/CapabilitiesUtil.js, src/CapabilitiesUtil/CapabilitiesUtil.spec.js
=> Apply optional `proxyFn` by parsing of layers from GetCapabilities document.

src/MapUtil/MapUtil.js, src/MapUtil/MapUtil.spec.js
This adds the methods `zoomToFeatures` and `isInScaleRange` to the `MapUtil`.
=> Add methods zoomToFeatures & isInScaleRange

src/ProjectionUtil/ProjectionUtil.js, src/ProjectionUtil/ProjectionUtil.spec.js
This adds the methods `dToDms`, `dToDmm` and `zerofill` to the `ProjectionUtil`.
=> Add toDms, toDmm and zerofill methods

.eslintrc, package.json
=> chore(package): update eslint to version 6.0.1

package.json
=> chore(package): update documentation to version 12.0.2

package.json
=> chore(package): update documentation to version 12.1.1

.dependabot/config.yml
Initializes the dependabot configuration.
=> Init dependabot config

package-lock.json, package.json
This updates
* `xmldom` from `v0.3.0` to `v0.4.0`
* `node-pre-gyp` from `v0.15.0` to `v0.17.0`
`npm test` still passes for me.
=> Update two dependencies

package-lock.json
=> Update lockfile and fix 8765 low severity vulnerabilities

src/FeatureUtil/FeatureUtil.spec.js, src/GeometryUtil/GeometryUtil.js, src/GeometryUtil/GeometryUtil.spec.js, src/MeasureUtil/MeasureUtil.js, src/ProjectionUtil/ProjectionUtil.js
=> Fix common misspellings with codespell

src/PermalinkUtil/PermalinkUtil.js, src/PermalinkUtil/PermalinkUtil.spec.js, src/index.js
This util helps creating and applying a permalink for the given map.
Reads and writes links like
`http://fake?zoom=3&center=10;20&layers=peter;pan`
=> Add PermalinkUtil

src/PermalinkUtil/PermalinkUtil.js, src/PermalinkUtil/PermalinkUtil.spec.js
* Properly split array of permalink layers befory applying of its visibility in layer tree.
* Also introduces tiny help method to determine field separator for permalink parameters.
=> Fix layer visibility from permalink

package-lock.json
This fixes some issues from `npm audit`.
Please review.
=> Update package-lock.json / npm audit fix

tasks/update-gh-pages.js
github does no longer support https login for cli
=> chore: fix deploy script

src/AnimateUtil/AnimateUtil.js, src/CapabilitiesUtil/CapabilitiesUtil.js, src/LayerUtil/LayerUtil.js, src/MapUtil/MapUtil.js, src/PermalinkUtil/PermalinkUtil.js
This PR replaces `OlLayer` with `OlLayerBase` as input parameters wherever possible to widen the accepted parameters.
It also fixes some parameter types.
=> fix: improve typings

package-lock.json, package.json, src/AnimateUtil/AnimateUtil.js, src/AnimateUtil/AnimateUtil.spec.js, src/CapabilitiesUtil/CapabilitiesUtil.js, src/FeatureUtil/FeatureUtil.js, src/GeometryUtil/GeometryUtil.js, src/LayerUtil/LayerUtil.js, src/LayerUtil/LayerUtil.spec.js, src/MapUtil/MapUtil.js, src/MapUtil/MapUtil.spec.js, src/PermalinkUtil/PermalinkUtil.js, src/ProjectionUtil/ProjectionUtil.js, src/TestUtil.js, src/WfsFilterUtil/WfsFilterUtil.js, src/declarations.d.ts, tsconfig.json
This PR enables the typescript `strict` option.
Depends on https://github.com/terrestris/ol-util/pull/646
=> Enable strict

README.md, package-lock.json, package.json, src/LayerUtil/LayerUtil.js, watchBuild.js
- parses '[ol/source/Stamen](https://openlayers.org/en/latest/apidoc/module-ol_source_Stamen.html)' in inkmap layer mapper
- also adds a watchBuild script which serves as an improvement to `npm link` (credits to @simonseyock )
=> feat: parse more layer types

src/LayerUtil/LayerUtil.js
See title. @terrestris/devs Please review
=> Only print visible layers

src/LayerUtil/LayerUtil.js
See title. @terrestris/devs Please review
=> fix: use correct attribute for layer name

src/MapUtil/MapUtil.js
Replaces the instanceof check with a function that is specific for layergroups.
=> fix: replaces the instanceof check

CHANGELOG.md
=> Fix some typos in CHANGELOG.md

.releaserc
Title says it all. 
Plz review @terrestris/devs
=> Semantic release: set correct default branch

package-lock.json, package.json, src/CapabilitiesUtil/CapabilitiesUtil.ts, src/LayerUtil/LayerUtil.spec.ts, src/MapUtil/MapUtil.spec.ts, src/MapUtil/MapUtil.ts, src/TestUtil.ts
Upgrades `ol` package to version v7.x and sets proper peer dependency.
Also upgrades `geostyler-openlayers-parser` package to v4.0.0 to fix dependency resolving conflict.
The PR includes some post upgrade code adaptations as well as test and linting fixtures.
=> Upgrade to Openlayers7

src/WfsFilterUtil/WfsFilterUtil.spec.ts, src/WfsFilterUtil/WfsFilterUtil.ts
This PR reverts some changes related to `WFSFilterUtil` class introduced in https://github.com/terrestris/ol-util/pull/826.
In particular:
Reintroduce `attributeDetails` property as a nested object mapping feature types to an object of their attribute details like:
```
attributeDetails: {
featType1: {
attr1: {
matchCase: true,
type: 'number',
exactSearch: false
},
attr2: {
matchCase: false,
type: 'string',
exactSearch: true
}
},
featType2: {...}
}
```
This restores the original  behaviour of the `WFSFilterUtil` which was implemented before transformation to typescript and enables to configure multiple feature types with their attributes at once for filtering.
=> WfsFilterUitl: Restore attribute config object for multiple feature types

src/PermalinkUtil/PermalinkUtil.ts
@terrestris/devs Please review.
=> fix: include image layers in permalink

src/CapabilitiesUtil/CapabilitiesUtil.ts
@terrestris/devs Please review.
=> fix: fix extraction of legend url

src/MeasureUtil/MeasureUtil.spec.ts
One might also argue to remove these existance tests, as they aren't super useful.
Please review.
=> Fix some (trivial) tests, remove copy & paste mistakes

src/LayerUtil/LayerUtil.ts
This fixes the source type determination for print layers by checking for exisiting specific functions instead of constructor names, as the latter did not work in production builds.
This is only needed because inkmap currently not supports ol-versions > 6.14
=> fix: source type detection in production builds

README.md
=> Minor: Fix typo in readme

.github/workflows/on-push-master.yml
Fix `semantic release` action, previous cmd was for older version.
@terrestris/devs
=> Fix semantic release cmd

.github/workflows/on-push-main.yml, .releaserc, README.md
Rename the default branch from `master` to `main`.
=> refactor: use main as default branch name

README.md, package-lock.json, package.json
* Remove unused `np` package
* Remove no longer supported snyk badge
=> Minor cleanups

package-lock.json, package.json, src/LayerUtil/LayerUtil.ts, src/PermalinkUtil/PermalinkUtil.spec.ts
Upgrade OpenLayers to version 8.0.0 and perform some code adaptations due to upgrade.
* set ol peer dependency to version 8
=> Upgrade to OpenLayers 8.x

.github/workflows/on-push-main.yml
This should fix the failing [pipeline](https://github.com/terrestris/ol-util/actions/runs/6237556945/job/16931421118).
@terrestris/devs
=> chore: fix sbom commit

.github/workflows/on-push-main.yml, README.md, sbom.json
=> chore: update readme

src/MapUtil/MapUtil.spec.ts, src/MapUtil/MapUtil.ts
=> feat: add util to calculate center and scale to fit in mapview
